#!/usr/bin/env python3

""" The WxFactory model """

import argparse
import datetime
import os.path
import sys

from mpi4py import MPI
import numpy


class ConfigOptionsAction(argparse.Action):
    def __init__(self, option_strings, dest, **kwargs):
        super().__init__(option_strings, dest, default=argparse.SUPPRESS, **kwargs)

    def __call__(self, parser, namespace, values, option_string, **kwargs) -> None:
        from common import load_default_schema

        schema = load_default_schema()
        if values == "md":
            print(f"{schema.to_string(True)}")
        else:
            print(f"Config options:\n{schema.to_string(False)}")

        parser.exit()


def main():
    """Execute a WxFactory simulation.

    This function drives the program: read and validate command-line options, then create and run a simulation."""

    src_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "wx_factory")
    sys.path.append(src_dir)

    args = None
    rank = MPI.COMM_WORLD.rank

    # Doing the import here allows to output potential errors from a single PE, making them much easier to deal with.
    try:
        from simulation import Simulation
        import wx_mpi
    except (ImportError, NameError) as e:
        if rank == 0:
            print(e)
            raise
        sys.exit(-1)

    # Only rank 0 parses the arguments
    with wx_mpi.SingleProcess() as s, wx_mpi.Conditional(s):
        parser = argparse.ArgumentParser(description="Solve NWP problems with GEF!")
        parser.add_argument("--profile", action="store_true", help="Produce an execution profile when running")
        parser.add_argument("config", type=str, help="File that contains simulation parameters")
        parser.add_argument(
            "--show-every-crash", action="store_true", help="In case of an exception, show output from alllllll PEs"
        )
        parser.add_argument(
            "--numpy-warn-as-except", action="store_true", help="Raise an exception if there is a numpy warning"
        )
        parser.add_argument("--ignore-numpy-warnings", action="store_true", help="Suppress runtime warnings from numpy")
        parser.add_argument(
            "--config-options",
            action=ConfigOptionsAction,
            type=str,
            nargs="?",
            help="List all possible configuration options and stop",
        )

        args = parser.parse_args()

        print(f'Start time : {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', flush=True)

        if not os.path.exists(args.config):
            raise ValueError(f"Config file does not seem to exist: {args.config}")

    args = MPI.COMM_WORLD.bcast(args, root=0)

    try:
        import cProfile

        # Start profiling
        pr = None
        if args.profile:
            pr = cProfile.Profile()
            pr.enable()

        numpy.set_printoptions(suppress=True, linewidth=256)
        if args.ignore_numpy_warnings:
            numpy.seterr(all="ignore")

        if args.numpy_warn_as_except:
            numpy.seterr(all="raise")

        # Initialize simulation
        sim = Simulation(args.config)

        # This is the actual run
        sim.run()

        # Stop profiling and store result to disk
        if args.profile and pr:
            pr.disable()

            out_file = f"prof_{rank:04d}.out"
            pr.dump_stats(out_file)

    except (Exception, KeyboardInterrupt) as e:  # KeyboardInterrupt does not seem to be caught with just "Exception"...

        try:
            if rank == 0:
                sim.output.finalize(0.0)
        except UnboundLocalError:
            pass
        finally:

            sys.stdout.flush()
            if args and args.show_every_crash:
                raise e

            if isinstance(e, KeyboardInterrupt):
                if rank == 0:
                    print(f"{rank:5d} Keyboard interrupt")
                sys.exit(130)

            if rank == 0:
                print(f"There was an error while running GEF. Only rank 0 is printing the traceback:")
                raise e

            sys.exit(-1)


if __name__ == "__main__":
    main()
