# DCMIP-2012 test 4-1: Baroclinic Instability

[Grid]

grid_type = cubed_sphere
lambda0 = 0.0
phi0 = 0.0
alpha0 = 0.0

ztop = 44000.0

vertical_coord = gal_chen


[Test_case]

equations = euler

# DCMIP recommends the shallow-atmosphere formulation.
depth_approx = shallow

case_number = 41


[Time_integration]

# Simulation end time in seconds.
t_end = 3600

dt = 1

time_integrator = epi2
jacobian_method = fd
exponential_solver = pmex
krylov_mmax = 32
tolerance = 1.2e-7


[Spatial_discretization]

num_solpts = 5

num_elements_horizontal = 18

num_elements_vertical = 6

# Weak post-step modal filter
expfilter_apply = 0
expfilter_order = 4
expfilter_cutoff = 0.5
expfilter_strength = 0.1


[Output_options]

stat_freq = 0

# With dt = 1 s, output every 5 model steps = every 5 s.
output_freq = 5

base_output_file = dcmip41


[Device]

precision = double
pytorch_device = cuda