# DCMIP-2012 test 4-1: Baroclinic Instability


[General]
equations = euler
depth_approx = shallow

[Grid]
grid_type = cubed_sphere
lambda0 = 0.0
phi0 = 0.0
alpha0 = 0.0
ztop = 44000.0

[Test_case]
case_number = 41

[Time_integration]
# The document specifies 3600 s in unscaled units (125 scaled hours).
t_end = 360
dt = 1
time_integrator = epi2
jacobian_method = fd
exponential_solver = pmex
krylov_mmax = 32
tolerance = 1.2e-7

[Spatial_discretization]
# 80 nodal points per panel edge (nominally 1 degrees).
num_solpts = 5
num_elements_horizontal = 18
num_elements_vertical = 6
# Weak post-step modal filter
expfilter_apply = 0
expfilter_order = 4
expfilter_cutoff = 0.5
expfilter_strength = 0.1

[Output_options]
stat_freq = 0
output_freq = 5
base_output_file = dcmip41

[System]
# Mixed precision stores the state and most runtime arrays in single precision while retaining
# double precision in accuracy-sensitive construction and solver operations.
precision = double
pytorch_device = cuda
