Test case:

   # Possible values
   #   1 : constant
   #   2 : gaussian
   case_number: 1

Time integration:
   # Time step
   dt: 5.

   # End time of the simulation in sec
   t_end: 600

   # Time integration scheme
   # Possible values : "epi2" : 2n order exponential propagation iterative
   #                   "epi3" : 3rd order exponential propagation iterative (Recommended)
   time_integrator: "epi3"


   # Initial size of the Krylov space. Stay constant for phipm, but can be updated dynamically with phipm_iom
   krylov_size: 10

   # Solver tolerance
   tolerance: 1e-7


Spatial discretization:

   # scaling of the diffusion coefficient
   Î±: 0.5

   # Degree of the reconstruction polynomial. The grid will have (degree+1)x(degree+1) nodal points in each elements.
   degree: 5

   # Number of element in x^1 and x^2 directions
   # Each face of the cube have (nbElements x nbElements) elements, for a total of (6 x nbElements x nbElements) elements.
   nb_elements: 20

Plot options:

   # Print blockstats every "stat_freq" steps, 0 to disable.
   stat_freq: 1

   # Plot solution every "plot_freq" steps, 0 to disable.
   plot_freq: 1
