[Grid]
grid_type = cartesian3d


lateral_boundary = periodic

x0 = 0
x1 = 1
y0 = 0
y1 = 0.1
z0 = 0
z1 = 1

[Test_case]

equations = euler

# Possible values
#   1  = constant
#   2  = gaussian
#   3  = cold bubble
# 651  = Gresho Vortex
case_number = 651

[Time_integration]
dt = 0.01
t_end = 1
time_integrator = epi3
exponential_solver = kiops
krylov_size = 10
tolerance = 1e-10
starting_step = 0
verbose_solver = 0
gmres_restart = 30

[Spatial_discretization]
num_solpts = 2
num_elements_horizontal = 15
num_elements_vertical   = 15
riemann_solver = ausm_plus_up

[Output_options]
stat_freq = 1
output_freq = 1
save_state_freq = 0
store_solver_stats = 1
output_dir = results_gresho_vortex_ausm_plus_up_mach_0d1
#ausm_simplified


[Device]
precision = double
pytorch_device = cuda
